name: secret-test-workflow

on:
  workflow_dispatch:

env:
  NODE_VERSION: "20.x"
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  install-build-test:
    runs-on: utuntu-latest

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - name: Install, Build and Test App
        run: |
          npm ci
          npm run build --if-present
          npm test

  stage-deploy:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Deploy to staging
        run: |
          echo "Deploying to staging in ${{env.AWS_DEFAULT_REGION}} region..."
